[workspace]
members = ["crates/fohmixer-proto", "crates/fohmixer-hub", "crates/fohmixer-ui"]
resolver = "2"

[workspace.package]
version = "0.1.0-dev.12"
edition = "2024"
authors = ["fohmixer contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/zbynekdrlik/fohmixer"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 1

[profile.mutants]
inherits = "test"
debug = "none"
